<?xml version="1.0" encoding="utf-8"?><Database Class="MyDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Contact">
    <Type Name="Contact">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="nvarchar(20)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="nvarchar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
      <Column Member="ContactType" Type="System.String" CanBeNull="false" IsDiscriminator="true" />
      <Association Name="Contact_CallRecord" Member="CallRecord" ThisKey="Id" OtherKey="ContactId" Type="CallRecord" />
      <Type Name="WorkContact" InheritanceCode="W">
        <Column Member="Company" Type="System.String" CanBeNull="false" />
      </Type>
      <Type Name="FamilyContact" InheritanceCode="F">
        <Column Member="Brithday" Type="System.String" CanBeNull="false" />
      </Type>
    </Type>
  </Table>
  <Table Name="" Member="CallRecord">
    <Type Name="CallRecord">
      <Column Member="Id" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Member="CallTime" Type="System.DateTimeOffset" CanBeNull="true" />
      <Column Member="CallSeconds" Type="System.Int32" CanBeNull="true" />
      <Column Member="ContactId" Type="System.Int32" CanBeNull="false" />
      <Association Name="Contact_CallRecord" Member="Contact" ThisKey="ContactId" OtherKey="Id" Type="Contact" IsForeignKey="true" />
    </Type>
  </Table>
</Database>